name: hoge

on:
  repository_dispatch:
    types: [hoge]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: cnfs/chap-3_step-1
    # Runs a single command using the runners shell
    - name: parse client payload
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.dryrun 
      run: |
        echo dryrun=${flag} >> ./.gitignore
        cat .gitignore
    - name: Run a one-line script
      env:
        name: ${{ github.event_name }}
        eventObjects:  ${{ toJson(github.event.client_payload) }}
        event:  ${{ github.event.types }}
      run: | 
        echo Hello, world! ${name}
        ls ./modules/appbase/
