name: test
on:
  pull_request:
    branches: [master]
    types: [closed]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: cnfs/chap-4_step-4

    - name: Dump GitHub context
      env:
        GITHUB_BASEREF: ${{ toJson(github.base_ref) }}
        GITHUB_HEADREF: ${{ toJson(github.head_ref) }}
        GITHUB_SHA: ${{ toJson(github.sha) }}
        GITHUB_REF: ${{ toJson(github.ref) }}
      run: |
        echo "$GITHUB_BASEREF"
        echo "$GITHUB_HEADREF"
        echo "$GITHUB_SHA"
        echo "$GITHUB_REF"
        ls ./modules/appbase/

